name: Sync nixpkgs fork with upstream

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync fork with upstream
        run: |
          gh repo sync znaniye/nixpkgs --source NixOS/nixpkgs --branch master --force
        env:
          GH_TOKEN: ${{ secrets.PAT }}
